@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Green Spaces Manager" as GSM
participant ":System" as System

activate GSM

    GSM -> System : requests to add a new task to the To-Do List
    activate System

        System --> GSM : displays a list of green spaces and prompts to choose one
    deactivate System

    GSM -> System : selects a green space
    activate System

    System --> GSM : prompts for task details (title, task description, degree of urgency \n(selectable), approximate duration)
    deactivate System

    GSM -> System : enters/selects task details
    activate System

    System --> GSM : displays entered data and asks for confirmation
    deactivate System

    GSM -> System : confirms the task details
    activate System

    System --> GSM : indicates task addition success
    deactivate System

deactivate GSM

@enduml
