@startuml

left to right direction

actor "Human Resources Manager (HRM)" as HRM
actor "Fleet Manager (FM)" as FM

usecase "UC1 Register Skills" as UC1
usecase "UC2 Register Job" as UC2
usecase "UC3 Register Collaborator with Job and Characteristics" as UC3
usecase "UC4 Assign Skills to Collaborator" as UC4
usecase "UC5 Generate Team Proposal" as UC5
usecase "UC6 Register Vehicle" as UC6
usecase "UC7 Register Vehicle Check-up" as UC7
usecase "UC8 List Vehicles for Check-up" as UC8

HRM --> UC1
HRM --> UC2
HRM --> UC3
HRM --> UC4
HRM --> UC5

FM --> UC6
FM --> UC7
FM --> UC8

@enduml





