@startuml

class HumanResourcesManager {
    name
    email
    phoneNumber
}

class Job {
    name
}

class Organization {
    name
    vatNumber
    website
    phoneNumber
    email
}

HumanResourcesManager "1" -- "*" Job : creates >
Organization "1" -- "*" Job : has >

@enduml