@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
autonumber
actor "User" as USER
participant "ToDoListUI" as UI
participant "ToDoListController" as CTRL
participant "Repositories" as Repositories
participant "ToDoListRepository" as ToDoListRepository
participant "ApplicationSession" as APP
participant "UserSession" as SESSION
participant "ToDoList" as TODOLIST

activate USER

USER -> UI : requests to create a new to-do list entry
activate UI
    UI --> USER : prompts for necessary details (e.g., task description, urgency, expected duration, location, status)
deactivate UI

USER -> UI : provides to-do list information (task description, urgency, expected duration, location, status, user email)
activate UI

    UI -> CTRL : addNewToDoListEntry(task description, urgency, expected duration, location, status, user email)
    activate CTRL

        CTRL -> Repositories : getRepositoriesInstance()
        activate Repositories

            Repositories --> CTRL : toDoListRepository
        deactivate Repositories

        CTRL -> APP: getAppInstance()
        activate APP

            APP -> CTRL: getCurrentSession()
        deactivate APP

        CTRL -> SESSION: getCurrentUserEmail()
        activate SESSION

            SESSION --> CTRL: user email
        deactivate SESSION

        CTRL -> TODOLIST : createNewToDoList(task description, urgency, expected duration, location, status, user email)
        activate TODOLIST

            TODOLIST -> TODOLIST : validate input
            TODOLIST -> ToDoListRepository : addNewEntry(TODOLIST)
        deactivate TODOLIST

        CTRL --> UI : notifies successful creation of the to-do list entry
deactivate CTRL

UI --> USER : confirms successful creation of the to-do list entry
deactivate UI

@enduml